#ifndef EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP
#define EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP

// Motors
#define MOTOR_A_SPEED 3
#define MOTOR_A_FORWARD 14
#define MOTOR_A_BACKWARDS 15

#define MOTOR_B_SPEED 2
#define MOTOR_B_FORWARD 16
#define MOTOR_B_BACKWARDS 17

#define MOTOR_MAX_SPEED 255

// Analog Gray Scale Sensors
#define GC_SENSOR_FRONT A14
#define GC_SENSOR_BACK A15

// Laser Range Sensors
#define LR_SENSOR_SIDE_BACK_RIGHT A7
#define LR_SENSOR_SIDE_FRONT_RIGHT A9
#define LR_SENSOR_SIDE_BACK_LEFT A6
#define LR_SENSOR_SIDE_FRONT_LEFT A8

// on board led
#define ON_BOARD_LED 13

#endif //EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP
