#ifndef EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP
#define EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP

// Motors
#define MOTOR_A_SPEED 3
#define MOTOR_A_FORWARD 14
#define MOTOR_A_BACKWARDS 15

#define MOTOR_B_SPEED 2
#define MOTOR_B_FORWARD 16
#define MOTOR_B_BACKWARDS 17

#define MOTOR_MAX_SPEED 255

// Analog Gray Scale Sensors
#define GC_SENSOR_FRONT A14
#define GC_SENSOR_BACK A14

#define RESET_BUTTON 52

// Laser Range Sensors
#define LR_SENSOR_RIGHT A12
#define LR_SENSOR_LEFT A10
#define LR_SENSOR_FRONT A6

#endif //EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP
