#ifndef EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP
#define EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP

// Motors
#define MOTOR_A_SPEED 2
#define MOTOR_A_FORWARD 14
#define MOTOR_A_BACKWARDS 15

#define MOTOR_B_SPEED 3
#define MOTOR_B_FORWARD 17
#define MOTOR_B_BACKWARDS 16

#define MOTOR_MAX_SPEED 255

// Analog Gray Scale Sensors
#define GC_SENSOR_FRONT A6
#define GC_SENSOR_BACK A7


//


#endif //EXTRATERRESTRIAL_MAZE_BOARDINFO_HPP
