#ifndef EXTRATERRESTRIAL_MAZE_BOARD_INFO_HPP
#define EXTRATERRESTRIAL_MAZE_BOARD_INFO_HPP

#define MOTOR_A_SPEED 2
#define MOTOR_A_FORWARD 14
#define MOTOR_A_BACKWARDS 15

#define MOTOR_B_SPEED 3
#define MOTOR_B_FORWARD 16
#define MOTOR_B_BACKWARDS 17



#endif //EXTRATERRESTRIAL_MAZE_BOARD_INFO_HPP
